# Generated by Django 2.2.6 on 2019-10-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=7)),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
